// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function compile(expression) {
  switch (expression.TAG | 0) {
    case /* Val */0 :
        var n = expression._0;
        return function (param) {
          return n;
        };
    case /* Add */1 :
        var right = expression._1;
        var left = expression._0;
        return function (param) {
          return compile(left)(undefined) + compile(right)(undefined) | 0;
        };
    case /* Sub */2 :
        var right$1 = expression._1;
        var left$1 = expression._0;
        return function (param) {
          return compile(left$1)(undefined) - compile(right$1)(undefined) | 0;
        };
    
  }
}

exports.compile = compile;
/* No side effect */
