// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Lexer = require("./Lexer.bs.js");
var Parser = require("./Parser.bs.js");
var Compiler = require("./Compiler.bs.js");

var input = "-1 - (2 - 3) + 4";

var run = Compiler.compile(Parser.parse(Lexer.lex(input)));

console.log(run(undefined));

exports.input = input;
exports.run = run;
/* run Not a pure module */
