// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.bs.js");
var Lexer = require("../src/Lexer.bs.js");

Jest.describe("Lexer", (function (param) {
        return Jest.test("it should lex", (function (param) {
                      return Jest.Expect.toEqual({
                                  hd: /* Num */{
                                    _0: -1
                                  },
                                  tl: {
                                    hd: /* Plus */1,
                                    tl: {
                                      hd: /* OpenPar */2,
                                      tl: {
                                        hd: /* Num */{
                                          _0: 20
                                        },
                                        tl: {
                                          hd: /* Plus */1,
                                          tl: {
                                            hd: /* Num */{
                                              _0: 3
                                            },
                                            tl: {
                                              hd: /* ClosePar */3,
                                              tl: /* [] */0
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }, Jest.Expect.expect(Lexer.lex("-1 + (20 + 3)")));
                    }));
      }));

/*  Not a pure module */
